# Site settings
title: 
header-img: img/home-bg.png
email: szilvia.hosser@gmail.com
copyright_name: kotkoda7
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kotkoda7
learn_profile: kotkoda7
email_username: szilvia.hosser@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
